"""
Utility functions for the Propagator class
"""
from typing import List, Tuple

from pennylane.operation import Observable


def remove_duplicate_observables(
    observables: List[Observable]
) -> Tuple[List[Observable], List[Observable]]:
    """
    Remove duplicate observables from a list of PennyLane observables.

    Two observables are considered duplicates if their `simplify().hash` is identical.

    This is to avoid redundant observables being generated by an ansatz,
    which can lead to unnecessary computations during propagation or expectation
    value evaluation.

    Parameters
    ----------
    observables : list[Observable]
        A list of PennyLane observables captured in a `QuantumTape`.

    Returns
    -------
    unique_observables : list[Observable]
        Observables with duplicates removed. Each observable is simplified first.
    removed_elements : list[Observable]
        Observables that were removed because a duplicate with the same hash
        already existed.
    """
    seen_hashes: set[int] = set()
    removed_elements: List[Observable] = []
    unique_observables: List[Observable] = []

    for tape_obs in observables:
        simplified = tape_obs.simplify()  # canonical form
        h = simplified.hash
        if h not in seen_hashes:
            unique_observables.append(simplified)
            seen_hashes.add(h)
        else:
            removed_elements.append(simplified)

    return unique_observables, removed_elements